### ISSUE TITLE
Подготовить БД psql 

### ISSUE THREAD

**Issue by kuznetsovandrey76** [Uniyar/Messenger-Express-Postgresql#7]
установить: SQL SHELL(psql)
исходники: 
https://www.postgresql.org/download/windows/
https://www.pgadmin.org/download/pgadmin-3-windows/

**Comment by kuznetsovandrey76** [comment]
name: `pwkuyymryylgca`
password: `1f10264803d3fbb548273870b7544c0b350cad494cb20e1cc94d692fab68534d`
host: `ec2-54-217-249-103.eu-west-1.compute.amazonaws.com`
port: `5432`
database: `dbkul1fdfjrnkp`

**Comment by kuznetsovandrey76** [comment]
`psql \! chcp 1251` - исправить шрифт
`\dt` - список таблиц
таблица содержит: `id`, `name`, `message`

**Comment by romankors** [comment]
Таблица создана
```
CREATE table messenger(
id serial primary key,
name varchar(50) not null,
messange varchar(280) not null
);
```

**Comment by kuznetsovandrey76** [comment]
Исправить поле `messange` на `message`

**Comment by romankors** [comment]
удалить таблицу: `DROP TABLE messenger;`
```
CREATE table messenger(
id serial primary key,
name varchar(50) not null,
message varchar(280) not null
);
```
вставка в таблицу: `INSERT INTO messenger VALUES (1, '<YOUR_NAME>', '<YOUR_MESSAGE>');`
просмотр содержимого: `SELECT * FROM messenger;`

**Comment by kuznetsovandrey76** [comment]
done
